feat: add functions, arguments and parameters md doc
resilia-br/wiki-tech pull request #13
Opened 2021-11-24 02:16 UTC by allankildare

## Descrição
Este PR tem o intuito de disponibilizar o primeiro arquivo `.md` sobre funções, parâmetros e argumentos. Nele abordei sobre o conceito, sintaxe e uso de funções, além de desmistificar o que é argumento e parâmetro, além disso, o material dessa vez disponibilizado ajuda a sanar e aprofundar bastante o conhecimento em funções.

Acha necessário abordar sobre _arrow functions_ neste documento?

2021-11-24 11:45 UTC, felipez3r0 commented on funcoes-argumentos-e-parametros.md
> +```javascript
Acho que essa parte aqui @allankildare não faz sentido nesse momento (vai acabar confundindo mais que ajudando)

2021-11-24 11:47 UTC, felipez3r0 requested changes
Na parte sobre o retorno de componentes React acho que vai confundir mais que ajudar, tira essa parte (28 a 35) e deixa só o exemplo anterior :)

2021-11-25 04:27 UTC, allankildare commented
> Na parte sobre o retorno de componentes React acho que vai confundir mais que ajudar, tira essa parte (28 a 35) e deixa só o exemplo anterior :)

Resolvido @felipez3r0 :)

2021-11-25 11:43 UTC, felipez3r0 approved these changes
Tudo ok! 👍

2021-11-25 18:19 UTC, merged