feat: add bootstrap md doc (#20)
resilia-br/wiki-tech pull request #21
Opened 2021-12-16 07:08 UTC by cafrangel

2021-12-20 04:21 UTC, allankildare commented
@cafrangel é um prazer te ter como contribuidora desse projeto e já gostaria de te parabenizar por esse documento muito bem feito :)
Só tenho alguns ajustes para comentar

2021-12-20 04:35 UTC, allankildare reviewed
Aqui está o que observei de possíveis melhorias

2021-12-20 04:35 UTC, allankildare commented on bootstrap.md
> +1. A forma mais rápida é com o **BootstrapCDN**, primeiro você deve copiar e colar o arquivo de estilo `<link>` dentro da `<head>` do seu arquivo .html antes de todos os outros arquivos de estilo:
Como se trata de uma documentação acho super válido explicitarmos o que é cada coisa.
Aqui ficou um pouco confuso o que é a tag `<link>`, no contexto que você mostrou aqui ela se trata de uma tag que define uma relação de folha de estilo com o caminho passado no atributo `href`.
Acho que uma substituição viável seria essa:
```
[...] deve copiar e colar a seguinte tag `<link>` dentro da tag`<head>`
```

2021-12-20 04:35 UTC, allankildare commented on bootstrap.md
> +Para estilizar os componentes é necessário incluir classes específicas que podem ser vistas na documentação do bootstrap, essas classes já possuem seus atributos e estilos prontos, mas podem ser cust
Aqui acho que é válido escrever Bootstrap com letra maiúscula

2021-12-20 04:35 UTC, allankildare commented on bootstrap.md
> +- [[Documentação] **Bootstrap em português**](https://getbootstrap.com.br/docs/4.1/getting-started/introduction/)
Aqui no projeto wiki-tech adotei os links em formato de variáveis. Isso pode ser observado em qualquer documento de minha autoria e é super simples.
Ao invés de passarmos os links direto na linha, criamos variáveis no início do documento que já armazenam esses links. A diferença é que chamamos pelo nome da variável e usamos colchetes ao invés de parênteses.
Por exemplo:
```markdown
[documentacao-bootstrap]: https://getbootstrap.com.br/docs/4.1/getting-started/introduction/

O seu texto começaria aqui...
...
## Onde posso aprender mais sobre?
- [[Documentação] **Bootstrap em português**][documentacao-bootstrap]
```
O resultado dos links seria o mesmo proposto por você :)

2021-12-20 04:42 UTC, cafrangel commented
Olá Allan, você pode alterar qualquer coisa sem problema :) só com relação às variáveis que eu usei como base o arquivo de css e nele os links não estão declarados como variáveis, bom dar uma olhada também.

2021-12-20 04:48 UTC, allankildare commented
> Olá Allan, você pode alterar qualquer coisa sem problema :) só com relação às variáveis que eu usei como base o arquivo de css e nele os links não estão declarados como variáveis, bom dar uma olhada também.

Excelente percepção @cafrangel! A gente vai descobrindo o que houve de errado assim mesmo hahaha obrigado pelo toque. Mais tarde farei os ajustes e ficará pendente apenas sua revisão :)

2021-12-20 21:44 UTC, allankildare requested changes
Fiz as sugestões iniciais, o que você achou @cafrangel?

2021-12-20 21:44 UTC, allankildare commented on bootstrap.md
> +Para estilizar os componentes é necessário incluir classes específicas que podem ser vistas na documentação do bootstrap, essas classes já possuem seus atributos e estilos prontos, mas podem ser cust
```suggestion
Para estilizar os componentes é necessário incluir classes específicas que podem ser vistas na documentação do Bootstrap, essas classes já possuem seus atributos e estilos prontos, mas podem ser customizáveis usando um CSS próprio.
```

2021-12-20 21:44 UTC, allankildare commented on bootstrap.md
> +1. A forma mais rápida é com o **BootstrapCDN**, primeiro você deve copiar e colar o arquivo de estilo `<link>` dentro da `<head>` do seu arquivo .html antes de todos os outros arquivos de estilo:
```suggestion
1. A forma mais rápida é com o **BootstrapCDN**, primeiro você deve copiar e colar a seguinte tag `<link>` (com relação de folha de estilo) dentro da tag `<head>` do seu arquivo .html antes de todos os outros arquivos de estilo:
```

2021-12-21 00:42 UTC, allankildare requested changes
E aqui finalizo as mudanças necessárias

2021-12-21 00:42 UTC, allankildare commented on bootstrap.md
> +<p align="center">
```suggestion
<!-- VARIAVEIS -->
[navbar-bootstrap]: https://getbootstrap.com.br/docs/4.1/components/navbar/
[cards-bootstrap]: https://getbootstrap.com.br/docs/4.1/components/card/
[formularios-bootstrap]: https://getbootstrap.com.br/docs/4.1/components/forms/
[bordas-bootsrap]: https://getbootstrap.com.br/docs/4.1/utilities/borders/
[carousel-bootstrap]: https://getbootstrap.com.br/docs/4.1/components/carousel/
[documentacao-bootstrap]: https://getbootstrap.com.br/docs/4.1/getting-started/introduction/
[o-que-e-bootstrap-alura]: https://www.alura.com.br/artigos/bootstrap?gclid=Cj0KCQiAweaNBhDEARIsAJ5hwbek8InX7djTWiCKZAiXHYKhyoFdYCmT0K-EsNqCtsg99BRPna5V16waAkbpEALw_wcB
[o-que-e-bootstrap-hostinger]: https://www.hostinger.com.br/tutoriais/o-que-e-bootstrap
[o-que-e-bootstrap-hostinger-yt]: https://www.youtube.com/watch?v=jsTJL6Da5wc&ab_channel=HostingerBrasil
<!-- FIM DAS VARIAVEIS -->
<p align="center">
```

2021-12-21 00:42 UTC, allankildare commented on bootstrap.md
> +- [[Vídeo] **Bootstrap (Guia para Iniciantes)** ](https://www.youtube.com/watch?v=jsTJL6Da5wc&ab_channel=HostingerBrasil)
```suggestion
### O que mais é possível fazer? 
O Bootstrap possui diversos componentes que podem ser utilizados em suas aplicações, com destaque para:
- [**Navbar**][navbar-bootstrap]
- [**Cards**][cards-bootstrap]
- [**Formulários**][formularios-bootstrap]
- [**Bordas**][bordas-bootsrap]
- [**Caroulsel**][carousel-bootstrap]

## Onde posso aprender mais sobre?
- [[Documentação] **Bootstrap em português**][documentacao-bootstrap]
- [[Artigo] **Bootstrap - O que é, como e quando usar?**][o-que-e-bootstrap-alura]
- [[Artigo] **O Que é Bootstrap? Guia para Iniciantes**][o-que-e-bootstrap-hostinger]
- [[Vídeo] **Bootstrap (Guia para Iniciantes)** ][o-que-e-bootstrap-hostinger-yt]

```

2021-12-22 00:07 UTC, allankildare approved these changes

2021-12-22 00:07 UTC, allankildare commented
@felipez3r0 estou aprovando esse PR agora, qualquer ajuste necessário posso subir um PR extra.

2021-12-22 00:08 UTC, merged