feat: add text editor md doc
resilia-br/wiki-tech pull request #5
Opened 2021-11-16 14:43 UTC by allankildare

## Descrição
Este PR tem o intuito de adicionar o primeiro documento .md sobre os editores de texto, basicamente expliquei as diferença entre editor de texto, editor de código e IDE. Ao final disponibilizei uma lista com 6 softwares recomendados, dando ênfase no VS Code.

OBS.: o PR #1 deve ser revisado e aprovado antes desse

2021-11-19 18:17 UTC, felipez3r0 requested changes
@allankildare consegue colocar alguns links nos editores? Se o pessoal quiser ir para o site saber mais ou fazer o download fica mais fácil

2021-11-20 07:49 UTC, allankildare commented
> @allankildare consegue colocar alguns links nos editores? Se o pessoal quiser ir para o site saber mais ou fazer o download fica mais fácil

Acabei de fazer isso, o que achou?

2021-11-22 16:50 UTC, felipez3r0 approved these changes
Aprovado! 👍

2021-11-22 16:51 UTC, felipez3r0 approved these changes
Aprovado! 👍

2021-11-22 19:38 UTC, merged